name: Checks & Tests

on:
  pull_request:
  push:
    branches: [master]


jobs:
  validate:
    name: Validate and Test Code
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1.15.4
        with:
          otp-version: 25
          elixir-version: 1.14

      - name: Install Dependencies
        run: mix deps.get

      - name: Compile
        run: mix compile --warnings-as-errors

      - name: Check Format
        run: mix format --check-formatted

      - name: Check Styling
        run: mix credo

      - name: Static Analysis
        run: mix dialyzer

      - name: Run tests
        run: GRAPHQL_KEY=${{secrets.GRAPHQL_KEY}} mix test
